### ISSUE TITLE
font family

### ISSUE THREAD

**Issue by farishkash** [EzekielSargent/prj-rev-bwfs-dasmoto#1]
Too much repetition with font family.  When you wrote the font family selector for body that should be sufficient.

If it wasn't working properly just to point out universal selectors should be first such as

```
body {
  font-family: Helvetica;
}
```

Otherwise the css style will be applied after everything else and may be overridden unintentionally.

**Comment by EzekielSargent** [comment]
Thank you for your feedback, and looking back on my code I completely agree with this. I think I followed the spec sheet too formerly and when it came to the body styling as you've put in above I didn't think about it being at top and deleting the other font family inputs. Thanks again! (PS I will look into that Flexbox Froggy link you provided)
